baseURL = "https://onlw.github.io/"
languageCode = "en-us"
title = "åˆ†24æœŸä¹°æ³¡é¢ğŸœ"
theme = "kagome"
paginate = 7
copyright = "Â© 2021 <a href=\"\">kagome</a>."
hasCJKLanguage = true

# è®¾ç½®categories
[taxonomies]
  category = 'categories'
  tag = 'tags'

# ä½œè€…ä¿¡æ¯
[author]
  name = "Who"
  email = "1216062928@qq.com"
  description = "äººç±»çš„æ‚²æ¬¢å¹¶ä¸ç›¸é€š"
  avatar = "https://s.gravatar.com/avatar/a0570f9d1887caa3f4e5c9df9706d15d?s=200&r=g&d=retro"

# èœå•/å¯¼èˆªæ 
[menu]
  # é¡¶éƒ¨å¯¼èˆªæ 
  [[menu.main]]
    identifier = "/"
    name = "HOME"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "/posts"
    name = "POSTS"
    url = "/posts"
    weight = 2
  [[menu.main]]
    identifier = "/message"
    name = "MESSAGE"
    url = "/message"
    weight = 3
  [[menu.main]]
    identifier = "/link"
    name = "LINK"
    url = "/link"
    weight = 4
  
  # åº•éƒ¨ç¤¾äº¤å›¾æ ‡
  [[menu.social]]
    identifier = "github"
    name = "github"
    url = "https://github.com/onlw"
    weight = 1
  [[menu.social]]
    identifier = "twitter"
    name = "twitter"
    weight = 2
  [[menu.social]]
    identifier = "instagram"
    name = "instagram"
    weight = 3
#  [[menu.social]]
#    identifier = "weibo"
#    name = "weibo"
#    url = "https://weibo.com/u/5561168966"
#    weight = 4
#  [[menu.social]]
#    identifier = "zhihu"
#    name = "zhihu"
#    url = "https://www.zhihu.com/people/miku-84"
#    weight = 5

# URLæ ¼å¼
[permalinks]
  posts = "/:section/:year:month:day:15:04/"
  files = "/:section/:year:month:day:15:04/"
  docs = "/:section/:year:month:day:15:04/"

# ä¸»é¢˜ç›¸å…³é…ç½®é¡¹
[params]
  keywords = ['theme', 'kagome']
  description = ""
  mainSections = ["posts"]
  # å›½å†…å¤‡æ¡ˆå·
  beian = ""
  # TOCç›®å½•å‡ºç°å­—ç¬¦é•¿åº¦é™åˆ¶
  toc_show_len = 1

  [params.analytics]
    baidu = ""

  [params.widget]
    # ç›¸å…³æ–‡ç« æ¨èæ•°é‡
    articles_count = 6
    # åˆ†ç±»ç›¸å…³æ˜¾ç¤ºæ•°é‡
    categories_count = 6
    # æ ‡ç­¾ç›¸å…³æ˜¾ç¤ºæ•°é‡
    tags_count = 12

  [params.aplayer]
    theme = "#b7daff"
    autoplay = false
    loop = "none"
    mutex = true

  [params.dplayer]
    theme = "#b7daff"
    autoplay = false
    loop = false
    mutex = true
